### ISSUE TITLE
eth template error

### ISSUE THREAD

**Issue by roymcmorran** [simp/pupmod-simp-network#80]
In line 167 of `templates/eth.erb` you specify `-timeout` but it should be `--timeout` with two dashes.

Result:
`Jul  3 17:52:14 hostname network[6337]: Unknown command: -timeout`

Also the 
`unless @dhclient_timeout.nil?`
condition surrounding this can never evaluate to true, because the manifest specifies a default value.

**Comment by rgardner4012** [comment]
> In line 167 of `templates/eth.erb` you specify `-timeout` but it should be `--timeout` with two dashes.
> 
> Result: `Jul 3 17:52:14 hostname network[6337]: Unknown command: -timeout`
What OS are you seeing this on? I haven't been able to recreate this issue. Generally I would expect a double - like you mention, but in this case it's a single from what I am seeing.
```
Usage: dhclient [-4|-6] [-SNTPI1dvrxc] [-nw] [-p <port>] [-D LL|LLT]
                [-s server-addr] [-cf config-file] [-lf lease-file]
                [-pf pid-file] [--no-pid] [-e VAR=val]
                [-I <dhcp-client-identifier>] [-B]
                [-H <host-name> | -F <fqdn.fqdn>] [-timeout <timeout>]
                [-V <vendor-class-identifier>]
                [-R <request option list>]
                [-sf script-file] [interface]
```

**Comment by op-ct** [comment]
Looks like there are a few differences in `dhclient` args―`-R` does something completely different in EL7 vs EL8!
